name: "ARM template tests"

on: [pull_request]

jobs:
  best-practices-test:
    name: "ARM template tests using arm-ttk"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test Metric ARM Templates using arm-ttk
        id: metricfilestest
        uses: aliencube/arm-ttk-actions@v0.3
        with:
          path: EventHubs/src/azuredeploy_metrics.json

      - name: Test BlockBlob ARM Templates using arm-ttk
        id: blockblobfilestest
        uses: aliencube/arm-ttk-actions@v0.3
        with:
          path: BlockBlobReader/src/blobreaderdeploy.json

  security-test:
    name: "ARM template tests using checkov"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test Metric ARM Templates using checkov
        id: metriccheckov
        uses: bridgecrewio/checkov-action@v12
        with:
          file: EventHubs/src/azuredeploy_metrics.json
          skip_check: CKV_AZURE_16,CKV_AZURE_17,CKV_AZURE_35
          quiet: false
          framework: arm
          output_format: cli
          output_bc_ids: true

      - name: Test BlockBlob ARM Templates using checkov
        id: blockblobcheckov
        uses: bridgecrewio/checkov-action@v12
        with:
          file: BlockBlobReader/src/blobreaderdeploy.json
          #skip_check: CKV_AZURE_16,CKV_AZURE_17,CKV_AZURE_35
          quiet: false
          framework: arm
          output_format: cli
          output_bc_ids: true
          #log_level: DEBUG
