name: "ARM template tests"
on: [workflow_dispatch, pull_request]

jobs:
  best-practices-test:
    name: "ARM template tests using arm-ttk"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Rename file 
        run: |
          cp EventHubs/src/azuredeploy_metrics.json EventHubs/src/mainTemplate.json 
          cd EventHubs/src
          find . -maxdepth 1 -type f -name '*.json' ! -name 'mainTemplate.json' -exec rm -f {} +

      - name: Test Metric ARM Templates using arm-ttk
        id: metricfilestest
        uses: microsoft/action-armttk@main
        with:
          workdir: EventHubs/src
          fail_on_error: true
          level: "info"

      - name: Rename file 
        run: |
          rm -rf arm-ttk
          cp BlockBlobReader/src/blobreaderdeploy.json BlockBlobReader/src/mainTemplate.json 
          cd BlockBlobReader/src
          find . -maxdepth 1 -type f -name '*.json' ! -name 'mainTemplate.json' -exec rm -f {} +
        
      - name: Test BlockBlob ARM Templates using arm-ttk
        id: blockblobfilestest
        uses: microsoft/action-armttk@main
        with:
          workdir: BlockBlobReader/src
          fail_on_error: true
          level: "info"

      - name: Rename file 
        run: |
          rm -rf arm-ttk
          cp BlockBlobReader/src/PremiumPlan/blobreaderdeploywithPremiumPlan.json BlockBlobReader/src/PremiumPlan/mainTemplate.json 
          cd BlockBlobReader/src/PremiumPlan
          find . -maxdepth 1 -type f -name '*.json' ! -name 'mainTemplate.json' -exec rm -f {} +
        
      - name: Test BlockBlob Premium Plan ARM Templates using arm-ttk
        id: blockblobpremiumplanfilestest
        uses: microsoft/action-armttk@main
        with:
          workdir: BlockBlobReader/src/PremiumPlan

          fail_on_error: true
          level: "info"

  security-test:
    name: "ARM template tests using checkov"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test Metric ARM Templates using checkov
        id: metriccheckov
        uses: bridgecrewio/checkov-action@master
        with:
          file: EventHubs/src/azuredeploy_metrics.json
          skip_check: CKV_AZURE_16,CKV_AZURE_17,CKV_AZURE_35
          quiet: false
          framework: arm
          output_format: cli
          output_bc_ids: true

      - name: Test BlockBlob ARM Templates using checkov
        id: blockblobcheckov
        uses: bridgecrewio/checkov-action@master
        with:
          file: BlockBlobReader/src/blobreaderdeploy.json
          skip_check: CKV_AZURE_16,CKV_AZURE_17,CKV_AZURE_35
          quiet: false
          framework: arm
          output_format: cli
          output_bc_ids: true
          log_level: DEBUG

      - name: Test BlockBlob Premium Plan Templates using checkov
        id: blockblobpremiumplancheckov
        uses: bridgecrewio/checkov-action@master
        with:
          file: BlockBlobReader/src/blobreaderdeploywithPremiumPlan.json
          skip_check: CKV_AZURE_16,CKV_AZURE_17,CKV_AZURE_35
          quiet: false
          framework: arm
          output_format: cli
          output_bc_ids: true
