name: "ARM template tests"
on: [workflow_dispatch, pull_request]

jobs:
  best-practices-test:
    name: "ARM template tests using arm-ttk"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test Metric ARM Templates using arm-ttk
        id: metricfilestest
        uses: microsoft/action-armttk@main
        with:
          armttkVersion: aka.ms/arm-ttk-latest
          workdir: EventHubs/src/azuredeploy_metrics.json
          fail_on_error: true
          level: "info"

      - name: Test BlockBlob ARM Templates using arm-ttk
        id: blockblobfilestest
        uses: aliencube/arm-ttk-actions@main
        with:
          path: BlockBlobReader/src/blobreaderdeploy.json

      - name: Test BlockBlob Premium Plan ARM Templates using arm-ttk
        id: blockblobpremiumplanfilestest
        uses: aliencube/arm-ttk-actions@main
        with:
          path: BlockBlobReader/src/blobreaderdeploywithPremiumPlan.json

  security-test:
    name: "ARM template tests using checkov"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test Metric ARM Templates using checkov
        id: metriccheckov
        uses: bridgecrewio/checkov-action@master
        with:
          file: EventHubs/src/azuredeploy_metrics.json
          skip_check: CKV_AZURE_16,CKV_AZURE_17,CKV_AZURE_35
          quiet: false
          framework: arm
          output_format: cli
          output_bc_ids: true

      - name: Test BlockBlob ARM Templates using checkov
        id: blockblobcheckov
        uses: bridgecrewio/checkov-action@master
        with:
          file: BlockBlobReader/src/blobreaderdeploy.json
          skip_check: CKV_AZURE_16,CKV_AZURE_17,CKV_AZURE_35
          quiet: false
          framework: arm
          output_format: cli
          output_bc_ids: true
          log_level: DEBUG

      - name: Test BlockBlob Premium Plan Templates using checkov
        id: blockblobpremiumplancheckov
        uses: bridgecrewio/checkov-action@master
        with:
          file: BlockBlobReader/src/blobreaderdeploywithPremiumPlan.json
          skip_check: CKV_AZURE_16,CKV_AZURE_17,CKV_AZURE_35
          quiet: false
          framework: arm
          output_format: cli
          output_bc_ids: true
