name: "ARM template toolkit test"

on: [pull_request]

jobs:
  arm-toolkit:
    name: "ARM template toolkit test"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test ARM Templates - files
        id: filestest
        uses: aliencube/arm-ttk-actions@v0.3
        with:
          path: EventHubs/src
          files: azuredeploy_metrics.json

      - name: Test result - files
        shell: bash
        continue-on-error: true
        run: |
          echo "${{ toJSON(fromJSON(steps.filestest.outputs.results)) }}"