name: "Package version tests"
on: [workflow_dispatch, pull_request]

jobs:
  package-version-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run npm outdated
        working-directory: BlockBlobReader/target/consumer_build
        run: npm outdated